namespace Ajiva.Installer.Core.Installer.Pack
{
    internal enum StructureSpecialFolder : byte
    {
        None = 0xFE,
        InstallLocation = 0xFD,

        BeginCustomFolders = 0x7F,

        // from windows environment stuff
        Desktop = 0x0,
        Programs = 0x2,
        MyDocuments = 0x5,
        Favorites = 0x6,
        Startup = 0x7,
        Recent = 0x8,
        SendTo = 0x9,
        StartMenu = 0xB,
        MyMusic = 0xD,
        MyVideos = 0xE,
        DesktopDirectory = 0x10,
        MyComputer = 0x11,
        NetworkShortcuts = 0x13,
        Fonts = 0x14,
        Templates = 0x15,
        CommonStartMenu = 0x16,
        CommonPrograms = 0x17,
        CommonStartup = 0x18,
        CommonDesktopDirectory = 0x19,
        ApplicationData = 0x1A,
        PrinterShortcuts = 0x1B,
        LocalApplicationData = 0x1C,
        InternetCache = 0x20,
        Cookies = 0x21,
        History = 0x22,
        CommonApplicationData = 0x23,
        Windows = 0x24,
        System = 0x25,
        ProgramFiles = 0x26,
        MyPictures = 0x27,
        UserProfile = 0x28,
        SystemX86 = 0x29,
        ProgramFilesX86 = 0x2A,
        CommonProgramFiles = 0x2B,
        CommonProgramFilesX86 = 0x2C,
        CommonTemplates = 0x2D,
        CommonDocuments = 0x2E,
        CommonAdminTools = 0x2F,
        AdminTools = 0x30,
        CommonMusic = 0x35,
        CommonPictures = 0x36,
        CommonVideos = 0x37,
        Resources = 0x38,
        LocalizedResources = 0x39,
        CommonOemLinks = 0x3A,
        CDBurning = 0x3B,
    }
}
